services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - sqlite_data:/app/db_volume
    env_file:
      - ./backend/.env 

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env 
    depends_on:
      - backend

volumes:
  sqlite_data:
